### ISSUE TITLE
CECC2020

### ISSUE THREAD

**Issue by yyy24601** [tilleyd/cec2017-py#3]
Do you have the cec2020 benchmark function（python）?

**Comment by tilleyd** [comment]
Hi @yyy24601, no unfortunately not. This repository only includes functions specified for the 2017 benchmark suite.

I don't intend for this repository to contain any newer functions, but feel free to create a fork that includes newer function definitions.

**Comment by yyy24601** [comment]
Dear Duncan Tilley,Thanks for u reply.
Could you send your articles to me, I want to read them.
Best wishes,
YANG




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Duncan ***@***.***&gt;; 
发送时间: 2022年3月28日(星期一) 下午2:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tilleyd/cec2017-py] CECC2020 (Issue #3)





 
Hi @yyy24601, no unfortunately not. This repository only includes functions specified for the 2017 benchmark suite.
 
I don't intend for this repository to contain any newer functions, but feel free to create a fork that includes newer function definitions.
 
&mdash;
